//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYSAdmin.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.BasicAmenities = new HashSet<BasicAmenity>();
            this.HouseDescriptions = new HashSet<HouseDescription>();
            this.HouseImages = new HashSet<HouseImage>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int HouseID { get; set; }
        public string HouseName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> LinkTypeID { get; set; }
    
        public virtual ICollection<BasicAmenity> BasicAmenities { get; set; }
        public virtual Block Block { get; set; }
        public virtual ICollection<HouseDescription> HouseDescriptions { get; set; }
        public virtual ICollection<HouseImage> HouseImages { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
